# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoldierUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('armyID', models.CharField(max_length=8)),
            ],
        ),
    ]
