# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_soldieruser_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('mileage', models.CharField(max_length=50)),
                ('distance_traveled', models.CharField(max_length=50)),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=9)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(max_length=256)),
            ],
        ),
        migrations.RemoveField(
            model_name='soldieruser',
            name='id',
        ),
        migrations.AlterField(
            model_name='soldieruser',
            name='armyID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='soldier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.SoldierUser'),
        ),
        migrations.AddField(
            model_name='drive',
            name='driverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SoldierUser'),
        ),
        migrations.AddField(
            model_name='drive',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Vehicle'),
        ),
    ]
