# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170221_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drive',
            old_name='distance_traveled',
            new_name='end_mileage',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='mileage',
            new_name='start_mileage',
        ),
        migrations.RenameField(
            model_name='drive',
            old_name='vehicle',
            new_name='vehicle_number',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='current_drive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Drive'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='expiration',
            field=models.DateField(),
        ),
    ]
