# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170221_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='approx_mileage',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drive',
            name='approx_time',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='current_drive',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Drive'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
    ]
