# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170222_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='approx_mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='approx_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='drive',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
