# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170221_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='end_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drive',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
