# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170221_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
