# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170222_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='drive',
            name='is_active',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
