# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_drive_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
